---
version: "3.3"
services:
    jenkins:
        build:
            context: ./jenkins
            args:
                dockergid: ${_CI_DOCKER_GID}  # Host docker gid
        restart: unless-stopped
        volumes:
            - /var/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp:/tmp
            - .:/opt/docker
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - 8080:8080
            - 50000:50000
